// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/website.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$0 from "./loaders/omie/omie/POST/estoqueAjuste_.ts";
import * as $$$1 from "./loaders/omie/omie/POST/estoqueLocal_.ts";
import * as $$$2 from "./loaders/omie/omie/POST/estoqueMovestoque_.ts";
import * as $$$3 from "./loaders/omie/omie/POST/estoquePosest_.ts";
import * as $$$4 from "./loaders/omie/omie/POST/financasContapagar_.ts";
import * as $$$5 from "./loaders/omie/omie/POST/financasContareceber_.ts";
import * as $$$6 from "./loaders/omie/omie/POST/financasLancamentocontas_.ts";
import * as $$$7 from "./loaders/omie/omie/POST/financasMf_.ts";
import * as $$$8 from "./loaders/omie/omie/POST/financasPesquisartitulos_.ts";
import * as $$$9 from "./loaders/omie/omie/POST/geralCategoriaConta_.ts";
import * as $$$10 from "./loaders/omie/omie/POST/geralClientes_.ts";
import * as $$$11 from "./loaders/omie/omie/POST/geralContacorrente_.ts";
import * as $$$12 from "./loaders/omie/omie/POST/geralDepartamentos_.ts";
import * as $$$13 from "./loaders/omie/omie/POST/geralEmpresas_.ts";
import * as $$$14 from "./loaders/omie/omie/POST/geralParcelas_.ts";
import * as $$$15 from "./loaders/omie/omie/POST/geralProdutos_.ts";
import * as $$$16 from "./loaders/omie/omie/POST/geralProjetos_.ts";
import * as $$$17 from "./loaders/omie/omie/POST/geralVendedores_.ts";
import * as $$$18 from "./loaders/omie/omie/POST/produtosAtualizarTags_.ts";
import * as $$$19 from "./loaders/omie/omie/POST/produtosCaracteristicas_.ts";
import * as $$$20 from "./loaders/omie/omie/POST/produtosFamilia_.ts";
import * as $$$21 from "./loaders/omie/omie/POST/produtosNcm_.ts";
import * as $$$22 from "./loaders/omie/omie/POST/produtosPedido_.ts";
import * as $$$23 from "./loaders/omie/omie/POST/produtosPedidocompra_.ts";
import * as $$$24 from "./loaders/omie/omie/POST/produtosPesquisa_.ts";
import * as $$$25 from "./loaders/omie/omie/POST/produtosProduto_.ts";
import * as $$$26 from "./loaders/omie/omie/POST/produtosServico_.ts";
import * as $$$27 from "./loaders/omie/omie/POST/produtosTabelaprecos_.ts";
import * as $$$28 from "./loaders/omie/omie/POST/servicosOs_.ts";
import * as $$$29 from "./loaders/vtex/api/DELETE/pricingPrices:itemId.ts";
import * as $$$30 from "./loaders/vtex/api/DELETE/pricingPrices:itemIdFixed:priceTableId.ts";
import * as $$$31 from "./loaders/vtex/api/GET/pricingConfig.ts";
import * as $$$32 from "./loaders/vtex/api/GET/pricingMigration.ts";
import * as $$$34 from "./loaders/vtex/api/GET/pricingPipelineCatalog:priceTableId.ts";
import * as $$$33 from "./loaders/vtex/api/GET/pricingPipelineCatalog.ts";
import * as $$$35 from "./loaders/vtex/api/GET/pricingPrices:itemId.ts";
import * as $$$36 from "./loaders/vtex/api/GET/pricingPrices:itemIdComputed:priceTableId.ts";
import * as $$$38 from "./loaders/vtex/api/GET/pricingPrices:itemIdFixed:priceTableId.ts";
import * as $$$37 from "./loaders/vtex/api/GET/pricingPrices:itemIdFixed.ts";
import * as $$$39 from "./loaders/vtex/api/GET/pricingTables.ts";
import * as $$$40 from "./loaders/vtex/api/POST/pricingPrices:itemIdFixed:priceTableId.ts";
import * as $$$41 from "./loaders/vtex/api/PUT/pricingPipelineCatalog:priceTableId.ts";
import * as $$$42 from "./loaders/vtex/api/PUT/pricingPrices:itemId.ts";

const manifest = {
  "loaders": {
    "site/loaders/omie/omie/POST/estoqueAjuste_.ts": $$$0,
    "site/loaders/omie/omie/POST/estoqueLocal_.ts": $$$1,
    "site/loaders/omie/omie/POST/estoqueMovestoque_.ts": $$$2,
    "site/loaders/omie/omie/POST/estoquePosest_.ts": $$$3,
    "site/loaders/omie/omie/POST/financasContapagar_.ts": $$$4,
    "site/loaders/omie/omie/POST/financasContareceber_.ts": $$$5,
    "site/loaders/omie/omie/POST/financasLancamentocontas_.ts": $$$6,
    "site/loaders/omie/omie/POST/financasMf_.ts": $$$7,
    "site/loaders/omie/omie/POST/financasPesquisartitulos_.ts": $$$8,
    "site/loaders/omie/omie/POST/geralCategoriaConta_.ts": $$$9,
    "site/loaders/omie/omie/POST/geralClientes_.ts": $$$10,
    "site/loaders/omie/omie/POST/geralContacorrente_.ts": $$$11,
    "site/loaders/omie/omie/POST/geralDepartamentos_.ts": $$$12,
    "site/loaders/omie/omie/POST/geralEmpresas_.ts": $$$13,
    "site/loaders/omie/omie/POST/geralParcelas_.ts": $$$14,
    "site/loaders/omie/omie/POST/geralProdutos_.ts": $$$15,
    "site/loaders/omie/omie/POST/geralProjetos_.ts": $$$16,
    "site/loaders/omie/omie/POST/geralVendedores_.ts": $$$17,
    "site/loaders/omie/omie/POST/produtosAtualizarTags_.ts": $$$18,
    "site/loaders/omie/omie/POST/produtosCaracteristicas_.ts": $$$19,
    "site/loaders/omie/omie/POST/produtosFamilia_.ts": $$$20,
    "site/loaders/omie/omie/POST/produtosNcm_.ts": $$$21,
    "site/loaders/omie/omie/POST/produtosPedido_.ts": $$$22,
    "site/loaders/omie/omie/POST/produtosPedidocompra_.ts": $$$23,
    "site/loaders/omie/omie/POST/produtosPesquisa_.ts": $$$24,
    "site/loaders/omie/omie/POST/produtosProduto_.ts": $$$25,
    "site/loaders/omie/omie/POST/produtosServico_.ts": $$$26,
    "site/loaders/omie/omie/POST/produtosTabelaprecos_.ts": $$$27,
    "site/loaders/omie/omie/POST/servicosOs_.ts": $$$28,
    "site/loaders/vtex/api/DELETE/pricingPrices:itemId.ts": $$$29,
    "site/loaders/vtex/api/DELETE/pricingPrices:itemIdFixed:priceTableId.ts":
      $$$30,
    "site/loaders/vtex/api/GET/pricingConfig.ts": $$$31,
    "site/loaders/vtex/api/GET/pricingMigration.ts": $$$32,
    "site/loaders/vtex/api/GET/pricingPipelineCatalog:priceTableId.ts": $$$34,
    "site/loaders/vtex/api/GET/pricingPipelineCatalog.ts": $$$33,
    "site/loaders/vtex/api/GET/pricingPrices:itemId.ts": $$$35,
    "site/loaders/vtex/api/GET/pricingPrices:itemIdComputed:priceTableId.ts":
      $$$36,
    "site/loaders/vtex/api/GET/pricingPrices:itemIdFixed:priceTableId.ts":
      $$$38,
    "site/loaders/vtex/api/GET/pricingPrices:itemIdFixed.ts": $$$37,
    "site/loaders/vtex/api/GET/pricingTables.ts": $$$39,
    "site/loaders/vtex/api/POST/pricingPrices:itemIdFixed:priceTableId.ts":
      $$$40,
    "site/loaders/vtex/api/PUT/pricingPipelineCatalog:priceTableId.ts": $$$41,
    "site/loaders/vtex/api/PUT/pricingPrices:itemId.ts": $$$42,
  },
  "apps": {
    "site/apps/deco/website.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
