// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/website.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$1 from "./loaders/BeatSaver MCP/BeatSaver MCP/GET/apiCollaborations:key.ts";
import * as $$$0 from "./loaders/BeatSaver MCP/BeatSaver MCP/GET/apiCollaborations.ts";
import * as $$$2 from "./loaders/BeatSaver MCP/BeatSaver MCP/GET/apiDownloadHash:hash.ts";
import * as $$$3 from "./loaders/BeatSaver MCP/BeatSaver MCP/GET/apiDownloadKey:key:hash.ts";
import * as $$$4 from "./loaders/BeatSaver MCP/BeatSaver MCP/GET/apiMapsCollaborations:id.ts";
import * as $$$5 from "./loaders/BeatSaver MCP/BeatSaver MCP/GET/apiMapsHash:hash.ts";
import * as $$$6 from "./loaders/BeatSaver MCP/BeatSaver MCP/GET/apiMapsId:id.ts";
import * as $$$7 from "./loaders/BeatSaver MCP/BeatSaver MCP/GET/apiMapsLatest.ts";
import * as $$$8 from "./loaders/BeatSaver MCP/BeatSaver MCP/GET/apiMapsPlays:id.ts";
import * as $$$9 from "./loaders/BeatSaver MCP/BeatSaver MCP/GET/apiMapsUploader:id.ts";
import * as $$$10 from "./loaders/BeatSaver MCP/BeatSaver MCP/GET/apiMapsVotes:id.ts";
import * as $$$11 from "./loaders/BeatSaver MCP/BeatSaver MCP/GET/apiSearchText:searchType.ts";
import * as $$$12 from "./loaders/BeatSaver MCP/BeatSaver MCP/GET/apiUsersFind.ts";
import * as $$$13 from "./loaders/BeatSaver MCP/BeatSaver MCP/GET/apiUsersId:id.ts";
import * as $$$14 from "./loaders/BeatSaver MCP/BeatSaver MCP/GET/apiUsersName:name.ts";
import * as $$$15 from "./loaders/vtex/api/DELETE/pricingPrices:itemId.ts";
import * as $$$16 from "./loaders/vtex/api/DELETE/pricingPrices:itemIdFixed:priceTableId.ts";
import * as $$$17 from "./loaders/vtex/api/GET/pricingConfig.ts";
import * as $$$18 from "./loaders/vtex/api/GET/pricingMigration.ts";
import * as $$$20 from "./loaders/vtex/api/GET/pricingPipelineCatalog:priceTableId.ts";
import * as $$$19 from "./loaders/vtex/api/GET/pricingPipelineCatalog.ts";
import * as $$$21 from "./loaders/vtex/api/GET/pricingPrices:itemId.ts";
import * as $$$22 from "./loaders/vtex/api/GET/pricingPrices:itemIdComputed:priceTableId.ts";
import * as $$$24 from "./loaders/vtex/api/GET/pricingPrices:itemIdFixed:priceTableId.ts";
import * as $$$23 from "./loaders/vtex/api/GET/pricingPrices:itemIdFixed.ts";
import * as $$$25 from "./loaders/vtex/api/GET/pricingTables.ts";
import * as $$$26 from "./loaders/vtex/api/POST/pricingPrices:itemIdFixed:priceTableId.ts";
import * as $$$27 from "./loaders/vtex/api/PUT/pricingPipelineCatalog:priceTableId.ts";
import * as $$$28 from "./loaders/vtex/api/PUT/pricingPrices:itemId.ts";

const manifest = {
  "loaders": {
    "site/loaders/BeatSaver MCP/BeatSaver MCP/GET/apiCollaborations:key.ts":
      $$$1,
    "site/loaders/BeatSaver MCP/BeatSaver MCP/GET/apiCollaborations.ts": $$$0,
    "site/loaders/BeatSaver MCP/BeatSaver MCP/GET/apiDownloadHash:hash.ts":
      $$$2,
    "site/loaders/BeatSaver MCP/BeatSaver MCP/GET/apiDownloadKey:key:hash.ts":
      $$$3,
    "site/loaders/BeatSaver MCP/BeatSaver MCP/GET/apiMapsCollaborations:id.ts":
      $$$4,
    "site/loaders/BeatSaver MCP/BeatSaver MCP/GET/apiMapsHash:hash.ts": $$$5,
    "site/loaders/BeatSaver MCP/BeatSaver MCP/GET/apiMapsId:id.ts": $$$6,
    "site/loaders/BeatSaver MCP/BeatSaver MCP/GET/apiMapsLatest.ts": $$$7,
    "site/loaders/BeatSaver MCP/BeatSaver MCP/GET/apiMapsPlays:id.ts": $$$8,
    "site/loaders/BeatSaver MCP/BeatSaver MCP/GET/apiMapsUploader:id.ts": $$$9,
    "site/loaders/BeatSaver MCP/BeatSaver MCP/GET/apiMapsVotes:id.ts": $$$10,
    "site/loaders/BeatSaver MCP/BeatSaver MCP/GET/apiSearchText:searchType.ts":
      $$$11,
    "site/loaders/BeatSaver MCP/BeatSaver MCP/GET/apiUsersFind.ts": $$$12,
    "site/loaders/BeatSaver MCP/BeatSaver MCP/GET/apiUsersId:id.ts": $$$13,
    "site/loaders/BeatSaver MCP/BeatSaver MCP/GET/apiUsersName:name.ts": $$$14,
    "site/loaders/vtex/api/DELETE/pricingPrices:itemId.ts": $$$15,
    "site/loaders/vtex/api/DELETE/pricingPrices:itemIdFixed:priceTableId.ts":
      $$$16,
    "site/loaders/vtex/api/GET/pricingConfig.ts": $$$17,
    "site/loaders/vtex/api/GET/pricingMigration.ts": $$$18,
    "site/loaders/vtex/api/GET/pricingPipelineCatalog:priceTableId.ts": $$$20,
    "site/loaders/vtex/api/GET/pricingPipelineCatalog.ts": $$$19,
    "site/loaders/vtex/api/GET/pricingPrices:itemId.ts": $$$21,
    "site/loaders/vtex/api/GET/pricingPrices:itemIdComputed:priceTableId.ts":
      $$$22,
    "site/loaders/vtex/api/GET/pricingPrices:itemIdFixed:priceTableId.ts":
      $$$24,
    "site/loaders/vtex/api/GET/pricingPrices:itemIdFixed.ts": $$$23,
    "site/loaders/vtex/api/GET/pricingTables.ts": $$$25,
    "site/loaders/vtex/api/POST/pricingPrices:itemIdFixed:priceTableId.ts":
      $$$26,
    "site/loaders/vtex/api/PUT/pricingPipelineCatalog:priceTableId.ts": $$$27,
    "site/loaders/vtex/api/PUT/pricingPrices:itemId.ts": $$$28,
  },
  "apps": {
    "site/apps/deco/website.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
